[project]
name = "xsettings"
version = "1.4.0"
description = "Ways to document, centeralize, retreive and validate settings."
authors = [{ name = "Josh Orr", email = "josh@orr.blue" }]
requires-python = ">=3.14,<4"
readme = "README.md"
keywords = [
    "settings",
    "lazy",
    "configuration",
]
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: The Unlicense (Unlicense)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "setuptools>=82.0.1",
    "xsentinels>=1.2.0,<2",
    "xinject>=1.2.0,<2",
    "xloop>=1.1.0,<2",
    "xbool>=1.0.0,<2",
    "ciso8601>=2.3.0,<3",
]

[project.urls]
Repository = "https://github.com/joshorr/xsettings"

[dependency-groups]
dev = [
    "mkdocs-git-revision-date-plugin>=0.3.2,<0.4",
    "mkdocs>=1.4.0,<2",
    "mike>=2,<3",
    "pytest-pycodestyle>=2.3.0,<3",
    "pytest>=9,<10",
    "pdoc3>=0,<1",
    "mkdocs-material>=9,<10",
    "tomlkit>=0,<1",
    "mkdocs-autorefs>=1,<2",
    "mkdocstrings[python]>=1.0.3,<2",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["xsettings"]
module-root = ""

[build-system]
requires = ["uv_build>=0.11.23,<0.12.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--verbose --pycodestyle"
testpaths = ["tests", "xsettings"]

[tool.custom.xpublish]
extra-module-docs = ['xsentinels', 'xloop', 'xinject', 'xbool']

[tool.black]
line-length = 99
target_version = ['py38']
skip-string-normalization = 1
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
